<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('food')->insert([

            // Breakfast (category_id = 1)
            [
                'category_id' => 1,
                'name' => 'Pancakes',
                'description' => 'Fluffy pancakes served with maple syrup and butter.',
                'price' => 8.99,
                'img' => 'img/menu-1.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Omelette',
                'description' => 'Three eggs with cheese, mushrooms and fresh herbs.',
                'price' => 7.50,
                'img' => 'img/menu-2.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'French Toast',
                'description' => 'Golden toasted bread topped with cinnamon and honey.',
                'price' => 8.00,
                'img' => 'img/menu-3.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Avocado Toast',
                'description' => 'Fresh avocado on toasted bread with cherry tomatoes.',
                'price' => 9.50,
                'img' => 'img/menu-4.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Egg Benedict',
                'description' => 'Poached eggs with hollandaise sauce on English muffins.',
                'price' => 10.99,
                'img' => 'img/menu-5.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Breakfast Burrito',
                'description' => 'Scrambled eggs, cheese and vegetables wrapped in a tortilla.',
                'price' => 9.99,
                'img' => 'img/menu-6.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Fruit Bowl',
                'description' => 'Seasonal fresh fruits served with yogurt.',
                'price' => 6.99,
                'img' => 'img/menu-7.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Belgian Waffles',
                'description' => 'Crispy waffles served with berries and whipped cream.',
                'price' => 9.50,
                'img' => 'img/menu-8.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Lunch (category_id = 2)
            [
                'category_id' => 2,
                'name' => 'Chicken Burger',
                'description' => 'Grilled chicken breast with lettuce, tomato and cheese.',
                'price' => 11.99,
                'img' => 'img/menu-1.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Beef Burger',
                'description' => 'Juicy beef patty served with fries.',
                'price' => 12.99,
                'img' => 'img/menu-2.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Caesar Salad',
                'description' => 'Fresh lettuce with grilled chicken and parmesan cheese.',
                'price' => 10.50,
                'img' => 'img/menu-3.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Club Sandwich',
                'description' => 'Triple-layer sandwich with chicken, bacon and vegetables.',
                'price' => 10.99,
                'img' => 'img/menu-4.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Margherita Pizza',
                'description' => 'Classic pizza with mozzarella, tomato and basil.',
                'price' => 13.50,
                'img' => 'img/menu-5.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Chicken Wrap',
                'description' => 'Grilled chicken wrapped with fresh vegetables.',
                'price' => 9.99,
                'img' => 'img/menu-6.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Fish and Chips',
                'description' => 'Crispy fried fish served with golden fries.',
                'price' => 14.99,
                'img' => 'img/menu-7.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Pasta Alfredo',
                'description' => 'Creamy Alfredo pasta with grilled chicken.',
                'price' => 13.99,
                'img' => 'img/menu-8.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Dinner (category_id = 3)
            [
                'category_id' => 3,
                'name' => 'Grilled Salmon',
                'description' => 'Fresh salmon served with vegetables and lemon.',
                'price' => 18.99,
                'img' => 'img/menu-1.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Ribeye Steak',
                'description' => 'Premium grilled steak served with mashed potatoes.',
                'price' => 22.99,
                'img' => 'img/menu-2.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Roasted Chicken',
                'description' => 'Oven-roasted chicken with seasonal vegetables.',
                'price' => 16.99,
                'img' => 'img/menu-3.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Seafood Pasta',
                'description' => 'Pasta tossed with shrimp, mussels and creamy sauce.',
                'price' => 17.99,
                'img' => 'img/menu-4.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'BBQ Ribs',
                'description' => 'Slow-cooked ribs glazed with smoky barbecue sauce.',
                'price' => 20.99,
                'img' => 'img/menu-5.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Lamb Chops',
                'description' => 'Grilled lamb chops with rosemary and garlic.',
                'price' => 23.99,
                'img' => 'img/menu-6.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Shrimp Risotto',
                'description' => 'Creamy risotto topped with grilled shrimp.',
                'price' => 19.99,
                'img' => 'img/menu-7.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Chicken Parmesan',
                'description' => 'Breaded chicken baked with mozzarella and tomato sauce.',
                'price' => 17.50,
                'img' => 'img/menu-8.jpg',
                'available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
